kind: Template
apiVersion: v1
metadata:
  name: ${NAME}-imagestream-template
  labels:
    app-group: ${APP_GROUP}
    app-name: '{APP_NAME}'
    name: ${NAME}-imagestream-template
    role: db
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${NAME}
    spec:
      tags:
        - name: ${OUTPUT_IMAGE_TAG}
          annotations: null
          from:
            kind: ${SOURCE_IMAGE_KIND}
            namespace: ${SOURCE_IMAGE_NAMESPACE}
            name: ${SOURCE_IMAGE_NAME}:${SOURCE_IMAGE_TAG}
          # importPolicy:
          #   scheduled: true
parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the objects defined in this template.
    required: true
    value: db
  - name: APP_NAME
    displayName: App Name
    description: Used to group components together in the OpenShift console.
    required: true
    value: Sheriff-Scheduling
  - name: APP_GROUP
    displayName: App Group
    description: The name assigned to all of the deployments in this project.
    required: true
    value: ss
  - name: OUTPUT_IMAGE_TAG
    displayName: Output Image Tag
    description: The tag given to the built image.
    required: true
    value: latest
  - name: SOURCE_IMAGE_KIND
    displayName: Source Image Kind
    description: The 'kind' (type) of the  source image; typically ImageStreamTag, or DockerImage.
    required: true
    value: ImageStreamTag
  - name: SOURCE_IMAGE_NAME
    displayName: Source Image Name
    description: The name of the source image.
    required: true
    value: postgresql
  - name: SOURCE_IMAGE_TAG
    displayName: Source Image Tag
    description: The tag of the source image.
    required: true
    value: '12'
  - name: SOURCE_IMAGE_NAMESPACE
    displayName: Namespace
    required: true
    description: The Namespace where the ImageStream resides.
    value: openshift
